package com.esys.bpm.enums;

public enum ProcessComponent {
	ASSOCIATION, START, END, TASK, USER_TASK, SERVICE_TASK, SQL_TASK, SCRIPT_TASK, BUSINESS_RULE_TASK,
	NOTIFICATION_TASK, GATEWAY, EXCLUSIVE_GATEWAY, INCLUSIVE_GATEWAY, PARALLEL_GATEWAY, SUBPROCESS, TIMER_TASK,
	TEXT_ANNOTATION, SEQUENCE_FLOW
}
