spring:
  datasource:
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type: trace
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    com.esys.main: TRACE
    org.springframework.web: INFO # INFO is default but it's here to easily toggle it
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # to show sql binded values
  file: /u01/fmw/logs/domain_logs/ruleengine_app.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
    
    
google:
  recaptcha:
         key:
          site: 6Lfk6VkUAAAAAI6nyR09A63guG-s22nWlNPZpica
          secret: 6Lfk6VkUAAAAAG9CCK3cONdThFDeDl5iuhnahY9N
         siteVerifyUrl: https://www.google.com/recaptcha/api/siteverify 